"""Add status column to Feedback

Revision ID: 06b1c4a29bbb
Revises: 1a9caf0a744c
Create Date: 2025-01-21 10:33:06.502825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b1c4a29bbb'
down_revision = '1a9caf0a744c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
