"""Add image_path to Event

Revision ID: 35a4177cdbd6
Revises: 06b1c4a29bbb
Create Date: 2025-01-21 11:27:02.109455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a4177cdbd6'
down_revision = '06b1c4a29bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
